name: Node.js CI

on:
  push:
    branches: [ "master", "main" ] # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Automatically uses the latest LTS version

      - name: Install pnp as needed by Astro
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
