name: Node.js CI

on:
 push:
  branches: [ "master", "main" ]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   
   - name: Use Node.js LTS
     uses: actions/setup-node@v4
     with:
      node-version: 'lts/*'

   - name: Install pnp (Needed by Astro)
     run: npm i -g pnpm

   - name: Install dependencies
     run: pnpm install

   - name: Build project
     run: pnpm run build

   - name: Upload dist folder
     uses: actions/upload-artifact@v3
     with:
      name: astro-dist
      path: dist/
